// ============================================================
//  CLIENT CONFIGURATION — City of Murrieta 457 Plan
//  Swap this file for each new client. index.html is the
//  shared template and should never need to be edited.
// ============================================================

const clientConfig = {

    // ----------------------------------------------------------
    // Branding & Identity
    // ----------------------------------------------------------
    pageTitle:    'City of Murrieta - Deferred Compensation Plan',
    planName:     'City of Murrieta',
    planSubtitle: '457 Deferred Compensation Plan',

    // Logos (leave as empty string '' to hide)
    clientLogoUrl:    'murrieta-logo.png',
    fiduciaryLogoUrl: 'fiduciary-experts-logo.png',

    // Theme colors
    colors: {
        primary:      '#1a3a5c',
        primaryLight: '#2a5a8c',
        accent:       '#c8a951',
        accentLight:  '#e8d080'
    },

    // ----------------------------------------------------------
    // Login / CTA
    // ----------------------------------------------------------
    loginUrl:  'https://www.nrsforu.com/iApp/rsc/login.x',
    loginText: 'Log In to Nationwide',
    ctaTitle:  'Ready to Invest?',
    ctaBody:   'Log in to your Nationwide retirement account to select your investment allocation and start putting your plan into action.',

    // ----------------------------------------------------------
    // Footer
    // ----------------------------------------------------------
    footerName:       'City of Murrieta 457 Deferred Compensation Plan',
    footerDisclaimer: 'This tool is for educational purposes only and does not constitute investment advice.<br>Consult a financial advisor before making investment decisions. Past performance does not guarantee future results.<br>Fund performance data sourced from Yahoo Finance / Morningstar. Trailing returns as of 2/28/2026.',

    // ----------------------------------------------------------
    // Model Portfolios
    // Set to false if the client has no model portfolios.
    // When false, the target date fund becomes the Best Match.
    // ----------------------------------------------------------
    hasModelPortfolios: true,

    // ----------------------------------------------------------
    // Risk Profile → Fund Mapping
    // Scores are cumulative (timeScore + riskScore).
    // modelFund: null if client has no model portfolios.
    // ----------------------------------------------------------
    riskProfiles: [
        { maxScore: 10,       profile: 'Conservative',           modelFund: 'modelConservative',    allocationFund: 'wellesley' },
        { maxScore: 14,       profile: 'Moderately Conservative', modelFund: 'modelConservative',   allocationFund: 'lifestrategyConservative' },
        { maxScore: 18,       profile: 'Moderate',               modelFund: 'modelBalanced',        allocationFund: 'puritan' },
        { maxScore: 22,       profile: 'Moderate Growth',        modelFund: 'modelModerateGrowth',  allocationFund: 'lifestrategyGrowth' },
        { maxScore: 26,       profile: 'Moderately Aggressive',  modelFund: 'modelAggressive',      allocationFund: 'lifestrategyGrowth' },
        { maxScore: Infinity, profile: 'Aggressive',             modelFund: 'modelAggressive',      allocationFund: 'lifestrategyGrowth' }
    ],

    // ----------------------------------------------------------
    // Fund Data
    // Add, remove, or edit funds here for each client.
    // ----------------------------------------------------------
    fundData: {

        // ── Model Portfolios ───────────────────────────────────
        modelAggressive: {
            id: 'modelAggressive',
            type: 'Model Portfolio',
            name: 'Murrieta Aggressive Growth Model',
            badge: 'Best Match',
            shortDesc: 'A diversified portfolio of plan funds targeting 85% equity and 15% fixed income, designed for participants seeking maximum long-term growth.',
            riskLevel: 'Aggressive',
            stockBond: '85% Equity / 15% Fixed Income',
            expenseRatio: '0.13%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants with 20+ years to retirement who want maximum growth potential.',
            performance: { yr1: '16.95%', yr3: '18.96%', yr5: '9.28%', yr10: '11.75%' },
            stats: { sharpe3yr: '1.14', stdDev3yr: '11.62%', inception: '9/1/2015', rebalance: 'Quarterly' },
            description: 'The Murrieta Aggressive Growth Model is constructed using individual funds available in the City of Murrieta 457 plan. It targets approximately 85% equity across U.S. large-cap, mid-cap, small-cap, international, and real estate, with about 15% in fixed income for modest diversification. The portfolio is rebalanced quarterly and has outperformed its peer group benchmark since inception.',
            allocation: [
                '35.00% Vanguard Large Cap Index Admiral (VLCAX)',
                '14.98% Vanguard Growth Index Admiral (VIGAX)',
                '10.05% Vanguard Total Intl Stock Index Admiral (VTIAX)',
                '10.00% Baird Core Plus Bond Inst (BCOIX)',
                '9.95% Vanguard International Growth Adm (VWILX)',
                '5.08% Vanguard Real Estate Index Admiral',
                '5.00% iShares Russell Mid-Cap Index K (BRMKX)',
                '4.98% BlackRock High Yield K (BRHYX)',
                '4.96% iShares Russell Small/Mid-Cap Idx K (BSMKX)'
            ],
            pros: ['Highest growth potential: 18.96% annualized 3-year return', 'Low expense ratio of 0.13%', 'Broad diversification across 9 funds and multiple asset classes', 'Quarterly rebalancing maintains target allocation'],
            cons: ['Highest volatility (11.62% standard deviation)', 'Requires understanding that short-term losses are normal', 'Model portfolio is managed by the plan; participant selects it as a single option'],
            shortDesc_es: 'Una cartera diversificada de fondos del plan con objetivo de 85% en renta variable y 15% en renta fija, diseñada para participantes que buscan el máximo crecimiento a largo plazo.',
            description_es: 'El Modelo de Crecimiento Agresivo de Murrieta está construido con fondos individuales disponibles en el plan 457 de la Ciudad de Murrieta. Su objetivo es aproximadamente un 85% en renta variable y un 15% en renta fija para diversificación moderada. La cartera se rebalancea trimestralmente y ha superado a su grupo de referencia desde su inicio.',
            bestFor_es: 'Participantes con más de 20 años para jubilarse que desean el máximo potencial de crecimiento.',
            pros_es: ['Mayor potencial de crecimiento: 18.96% de rendimiento anualizado a 3 años', 'Bajo ratio de gastos de 0.13%', 'Amplia diversificación en 9 fondos y múltiples clases de activos', 'Rebalanceo trimestral mantiene la asignación objetivo'],
            cons_es: ['Mayor volatilidad (desviación estándar de 11.62%)', 'Requiere entender que las pérdidas a corto plazo son normales', 'La cartera modelo es gestionada por el plan; el participante la selecciona como una sola opción'],
            shortDesc_zh: '一个多元化的计划基金组合，目标为85%股票和15%固定收益，专为寻求最大长期增长的参与者设计。',
            description_zh: '穆里埃塔激进成长模型由市457计划中可用的单个基金构建。目标约为85%的股票资产和15%的固定收益。投资组合每季度再平衡，自成立以来表现优于同类基准。',
            bestFor_zh: '距退休20年以上、希望最大化增长潜力的参与者。',
            pros_zh: ['最高增长潜力：3年年化收益18.96%', '低费用率0.13%', '跨9个基金和多种资产类别的广泛分散投资', '季度再平衡维持目标配置'],
            cons_zh: ['最高波动性（标准差11.62%）', '需要理解短期亏损是正常的', '模型组合由计划管理；参与者将其作为单一选项选择'],
            shortDesc_ja: 'プラン資産の85%を株式、15%を債券に配分することを目標とした分散ポートフォリオで、最大限の長期成長を求める参加者向けです。',
            description_ja: 'ムリエタ積極成長モデルは、市の457プランで利用可能な個別ファンドで構成されています。約85%を米国・海外・不動産など多様な株式資産に、約15%を債券に配分します。四半期ごとにリバランスされ、設定来ベンチマークを上回る運用実績を持ちます。',
            bestFor_ja: '退職まで20年以上あり、最大限の成長ポテンシャルを求める参加者。',
            pros_ja: ['最高の成長ポテンシャル：3年年率リターン18.96%', '低い経費率0.13%', '9ファンド・複数資産クラスにわたる幅広い分散投資', '四半期リバランスで目標配分を維持'],
            cons_ja: ['最も高いボラティリティ（標準偏差11.62%）', '短期損失は通常であることの理解が必要', 'モデルポートフォリオはプランが管理し、参加者は単一の選択肢として選択'],
            shortDesc_tl: 'Isang diversified na portfolio ng mga pondo ng plano na may target na 85% equity at 15% fixed income, dinisenyo para sa mga kalahok na naghahanap ng pinakamataas na pangmatagalang paglago.',
            description_tl: 'Ang Murrieta Aggressive Growth Model ay binuo gamit ang mga indibidwal na pondo na available sa City of Murrieta 457 plan. Nagta-target ito ng humigit-kumulang 85% sa equity at 15% sa fixed income. Ang portfolio ay nire-rebalance tuwing quarter at nalampasan ang benchmark nito mula nang ilunsad.',
            bestFor_tl: 'Mga kalahok na may mahigit 20 taon bago magretiro na nagnanais ng pinakamataas na potensyal ng paglago.',
            pros_tl: ['Pinakamataas na potensyal ng paglago: 18.96% annualized na 3-taong return', 'Mababang expense ratio na 0.13%', 'Malawak na diversification sa 9 na pondo at maraming asset class', 'Quarterly rebalancing nagpapanatili ng target allocation'],
            cons_tl: ['Pinakamataas na volatility (11.62% standard deviation)', 'Kailangan ng pag-unawa na ang mga pagkalugi sa maikling panahon ay normal', 'Ang model portfolio ay pinamamahalaan ng plano; pinipili ito ng kalahok bilang isang solong opsyon'],
            shortDesc_pt: 'Uma carteira diversificada de fundos do plano com objetivo de 85% em renda variável e 15% em renda fixa, projetada para participantes que buscam o máximo crescimento a longo prazo.',
            description_pt: 'O Modelo de Crescimento Agressivo de Murrieta é construído com fundos individuais disponíveis no plano 457 da Cidade de Murrieta. Tem como objetivo aproximadamente 85% em renda variável e 15% em renda fixa. A carteira é rebalanceada trimestralmente e superou seu grupo de referência desde o início.',
            bestFor_pt: 'Participantes com mais de 20 anos para a aposentadoria que desejam o máximo potencial de crescimento.',
            pros_pt: ['Maior potencial de crescimento: retorno anualizado de 18,96% em 3 anos', 'Baixa taxa de despesas de 0,13%', 'Ampla diversificação em 9 fundos e múltiplas classes de ativos', 'Rebalanceamento trimestral mantém a alocação alvo'],
            cons_pt: ['Maior volatilidade (desvio padrão de 11,62%)', 'Requer compreensão de que perdas de curto prazo são normais', 'O portfólio modelo é gerenciado pelo plano; o participante o seleciona como uma única opção'],
            shortDesc_fr: 'Un portefeuille diversifié de fonds du plan ciblant 85 % en actions et 15 % en obligations, conçu pour les participants cherchant une croissance maximale à long terme.',
            description_fr: 'Le Modèle de Croissance Agressif de Murrieta est construit à partir de fonds individuels disponibles dans le plan 457 de la Ville de Murrieta. Il cible environ 85 % en actions et 15 % en obligations. Le portefeuille est rééquilibré trimestriellement et a surperformé son groupe de référence depuis sa création.',
            bestFor_fr: 'Participants ayant plus de 20 ans avant la retraite et souhaitant un potentiel de croissance maximal.',
            pros_fr: ['Plus grand potentiel de croissance : rendement annualisé de 18,96 % sur 3 ans', 'Faible ratio de frais de 0,13 %', 'Large diversification sur 9 fonds et plusieurs classes d\'actifs', 'Rééquilibrage trimestriel maintient l\'allocation cible'],
            cons_fr: ['Volatilité la plus élevée (écart-type de 11,62 %)', 'Nécessite de comprendre que les pertes à court terme sont normales', 'Le portefeuille modèle est géré par le plan ; le participant le sélectionne comme une option unique'],
            shortDesc_de: 'Ein diversifiziertes Portfolio aus Planfonds mit dem Ziel von 85 % Aktien und 15 % Anleihen, für Teilnehmer, die maximales langfristiges Wachstum anstreben.',
            description_de: 'Das Murrieta Aggressive Growth Modell besteht aus einzelnen Fonds des städtischen 457-Plans. Es strebt ca. 85 % in Aktien und 15 % in Anleihen an. Das Portfolio wird vierteljährlich neu gewichtet und hat seit Auflegung seine Vergleichsgruppe übertroffen.',
            bestFor_de: 'Teilnehmer mit mehr als 20 Jahren bis zur Rente, die maximales Wachstumspotenzial anstreben.',
            pros_de: ['Höchstes Wachstumspotenzial: 18,96 % annualisierte 3-Jahres-Rendite', 'Niedrige Kostenquote von 0,13 %', 'Breite Diversifikation über 9 Fonds und mehrere Anlageklassen', 'Vierteljährliche Neugewichtung hält Zielallokation aufrecht'],
            cons_de: ['Höchste Volatilität (Standardabweichung 11,62 %)', 'Erfordert das Verständnis, dass kurzfristige Verluste normal sind', 'Modellportfolio wird vom Plan verwaltet; Teilnehmer wählt es als eine einzige Option'],
            shortDesc_ru: 'Диверсифицированный портфель фондов плана с целевым распределением 85% акции / 15% облигации для участников, стремящихся к максимальному долгосрочному росту.',
            description_ru: 'Агрессивная модель роста Мурриета построена из отдельных фондов городского плана 457. Целевое распределение — около 85% акций и 15% облигаций. Портфель ребалансируется ежеквартально и с момента создания опережает эталонный показатель.',
            bestFor_ru: 'Участники с более чем 20 годами до выхода на пенсию, желающие максимального потенциала роста.',
            pros_ru: ['Наибольший потенциал роста: 18,96% годовая доходность за 3 года', 'Низкий коэффициент расходов 0,13%', 'Широкая диверсификация по 9 фондам и нескольким классам активов', 'Ежеквартальная ребалансировка поддерживает целевое распределение'],
            cons_ru: ['Наибольшая волатильность (стандартное отклонение 11,62%)', 'Требует понимания того, что краткосрочные потери нормальны', 'Модельный портфель управляется планом; участник выбирает его как единственный вариант']
        },

        modelModerateGrowth: {
            id: 'modelModerateGrowth',
            type: 'Model Portfolio',
            name: 'Murrieta Moderate Growth Model',
            badge: 'Best Match',
            shortDesc: 'A growth-oriented portfolio targeting 75% equity and 25% fixed income, designed for participants seeking strong growth with moderate risk.',
            riskLevel: 'Moderate Growth',
            stockBond: '75% Equity / 25% Fixed Income',
            expenseRatio: '0.10%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants with 15-25 years to retirement seeking growth with some downside protection.',
            performance: { yr1: '16.35%', yr3: '17.71%', yr5: '8.82%', yr10: '10.90%' },
            stats: { sharpe3yr: '1.16', stdDev3yr: '10.44%', inception: '9/1/2015', rebalance: 'Quarterly' },
            description: 'The Murrieta Moderate Growth Model targets 75% equity and 25% fixed income. It includes broad U.S. equity exposure, international diversification, real estate, and a meaningful bond allocation through intermediate-term and core-plus bond funds. The portfolio has delivered strong risk-adjusted returns with a 1.16 Sharpe ratio over 3 years.',
            allocation: [
                '40.00% Vanguard Large Cap Index Admiral (VLCAX)',
                '15.00% Vanguard Interm-Term Bond Index Adm (VBILX)',
                '10.00% Vanguard Growth Index Admiral (VIGAX)',
                '10.00% Vanguard Total Intl Stock Index Admiral (VTIAX)',
                '5.00% Baird Core Plus Bond Inst (BCOIX)',
                '5.00% BlackRock High Yield K (BRHYX)',
                '5.00% Vanguard International Growth Adm (VWILX)',
                '5.00% iShares Russell Mid-Cap Index K (BRMKX)',
                '3.00% Vanguard Real Estate Index Admiral',
                '2.00% iShares Russell Small/Mid-Cap Idx K (BSMKX)'
            ],
            pros: ['Strong growth with moderate risk: 17.71% annualized 3-year return', 'Best Sharpe ratio among models (1.16)', 'Very low expense ratio of 0.10%', 'Quarterly rebalancing maintains target allocation'],
            cons: ['Moderate volatility (10.44% standard deviation)', 'Less growth potential than the Aggressive model', 'Model portfolio is managed by the plan; participant selects it as a single option'],
            shortDesc_es: 'Una cartera orientada al crecimiento con objetivo de 75% en renta variable y 25% en renta fija, diseñada para crecimiento sólido con riesgo moderado.',
            description_es: 'El Modelo de Crecimiento Moderado de Murrieta tiene como objetivo un 75% en renta variable y un 25% en renta fija. Incluye exposición amplia a renta variable de EE.UU., diversificación internacional y una significativa asignación en bonos. Ha generado sólidos rendimientos ajustados al riesgo con un ratio de Sharpe de 1.16 en 3 años.',
            bestFor_es: 'Participantes con 15-25 años para jubilarse que buscan crecimiento con cierta protección frente a caídas.',
            pros_es: ['Crecimiento sólido con riesgo moderado: 17.71% de rendimiento anualizado a 3 años', 'Mejor ratio de Sharpe entre los modelos (1.16)', 'Muy bajo ratio de gastos de 0.10%', 'Rebalanceo trimestral mantiene la asignación objetivo'],
            cons_es: ['Volatilidad moderada (desviación estándar de 10.44%)', 'Menor potencial de crecimiento que el modelo Agresivo', 'La cartera modelo es gestionada por el plan; el participante la selecciona como una sola opción'],
            shortDesc_zh: '以75%股票和25%固定收益为目标的成长型投资组合，旨在以中等风险实现稳健增长。',
            description_zh: '穆里埃塔中度成长模型目标为75%股票和25%固定收益，包括美国股票敞口、国际分散投资和较大的债券配置。3年夏普比率为1.16，风险调整后收益表现优异。',
            bestFor_zh: '距退休15-25年、寻求增长同时具备一定下行保护的参与者。',
            pros_zh: ['中等风险下的强劲增长：3年年化收益17.71%', '模型中最佳夏普比率（1.16）', '极低费用率0.10%', '季度再平衡维持目标配置'],
            cons_zh: ['中等波动性（标准差10.44%）', '增长潜力低于激进模型', '模型组合由计划管理；参与者将其作为单一选项选择'],
            shortDesc_ja: '株式75%・債券25%を目標とした成長志向ポートフォリオで、中程度のリスクで強いリターンを求める参加者向け。',
            description_ja: 'ムリエタ中程度成長モデルは75%株式・25%債券を目標とし、米国株・海外・債券に広く分散投資します。3年シャープレシオ1.16と優れたリスク調整後リターンを実現しています。',
            bestFor_ja: '退職まで15〜25年あり、成長と下落防御のバランスを求める参加者。',
            pros_ja: ['中程度のリスクで強い成長：3年年率リターン17.71%', 'モデル中最高のシャープレシオ（1.16）', '非常に低い経費率0.10%', '四半期リバランスで目標配分を維持'],
            cons_ja: ['中程度のボラティリティ（標準偏差10.44%）', '積極型モデルより成長ポテンシャルが低い', 'モデルポートフォリオはプランが管理'],
            shortDesc_tl: 'Isang portfolio na nakatuon sa paglago na may target na 75% equity at 25% fixed income para sa matibay na paglago na may katamtamang panganib.',
            description_tl: 'Ang Murrieta Moderate Growth Model ay nagta-target ng 75% equity at 25% fixed income. Kasama rito ang malawak na exposure sa U.S. equity, internasyonal na diversification, at makabuluhang bond allocation. Nagpapakita ito ng 1.16 Sharpe ratio sa loob ng 3 taon.',
            bestFor_tl: 'Mga kalahok na may 15-25 taon bago magretiro na naghahanap ng paglago na may ilang proteksyon sa pagbaba.',
            pros_tl: ['Matibay na paglago na may katamtamang panganib: 17.71% annualized 3-taong return', 'Pinakamahusay na Sharpe ratio sa mga modelo (1.16)', 'Napakababang expense ratio na 0.10%', 'Quarterly rebalancing nagpapanatili ng target allocation'],
            cons_tl: ['Katamtamang volatility (10.44% standard deviation)', 'Mas mababang potensyal ng paglago kaysa sa Aggressive model', 'Ang model portfolio ay pinamamahalaan ng plano'],
            shortDesc_pt: 'Uma carteira voltada ao crescimento com meta de 75% em renda variável e 25% em renda fixa, para crescimento sólido com risco moderado.',
            description_pt: 'O Modelo de Crescimento Moderado de Murrieta tem como meta 75% em renda variável e 25% em renda fixa. Inclui exposição à renda variável americana, diversificação internacional e alocação significativa em títulos. Apresenta índice de Sharpe de 1,16 em 3 anos.',
            bestFor_pt: 'Participantes com 15-25 anos para a aposentadoria buscando crescimento com proteção contra quedas.',
            pros_pt: ['Crescimento sólido com risco moderado: retorno anualizado de 17,71% em 3 anos', 'Melhor índice de Sharpe entre os modelos (1,16)', 'Taxa de despesas muito baixa de 0,10%', 'Rebalanceamento trimestral mantém a alocação alvo'],
            cons_pt: ['Volatilidade moderada (desvio padrão de 10,44%)', 'Menor potencial de crescimento que o modelo Agressivo', 'O portfólio modelo é gerenciado pelo plano'],
            shortDesc_fr: 'Un portefeuille orienté croissance ciblant 75 % en actions et 25 % en obligations, pour une croissance solide avec un risque modéré.',
            description_fr: 'Le Modèle de Croissance Modérée de Murrieta cible 75 % en actions et 25 % en obligations. Il offre une large exposition aux actions américaines, une diversification internationale et une allocation obligataire significative. Son ratio de Sharpe sur 3 ans est de 1,16.',
            bestFor_fr: 'Participants avec 15 à 25 ans avant la retraite cherchant une croissance avec protection partielle.',
            pros_fr: ['Croissance solide avec risque modéré : rendement annualisé de 17,71 % sur 3 ans', 'Meilleur ratio de Sharpe des modèles (1,16)', 'Très faible ratio de frais de 0,10 %', 'Rééquilibrage trimestriel maintient l\'allocation cible'],
            cons_fr: ['Volatilité modérée (écart-type de 10,44 %)', 'Potentiel de croissance inférieur au modèle Agressif', 'Le portefeuille modèle est géré par le plan'],
            shortDesc_de: 'Ein wachstumsorientiertes Portfolio mit 75 % Aktien und 25 % Anleihen für starkes Wachstum bei moderatem Risiko.',
            description_de: 'Das Murrieta Moderate Growth Modell strebt 75 % Aktien und 25 % Anleihen an. Es bietet breite US-Aktienexposition, internationale Diversifikation und bedeutende Anleiheanteile. Die Sharpe Ratio beträgt 1,16 über 3 Jahre.',
            bestFor_de: 'Teilnehmer mit 15–25 Jahren bis zur Rente, die Wachstum mit Absicherung suchen.',
            pros_de: ['Starkes Wachstum bei moderatem Risiko: 17,71 % annualisierte 3-Jahres-Rendite', 'Beste Sharpe Ratio unter den Modellen (1,16)', 'Sehr niedrige Kostenquote von 0,10 %', 'Vierteljährliche Neugewichtung'],
            cons_de: ['Moderate Volatilität (Standardabweichung 10,44 %)', 'Weniger Wachstumspotenzial als das Aggressive Modell', 'Modellportfolio wird vom Plan verwaltet'],
            shortDesc_ru: 'Портфель роста с целевым распределением 75% акции / 25% облигации для устойчивого роста при умеренном риске.',
            description_ru: 'Модель умеренного роста Мурриета нацелена на 75% акций и 25% облигаций. Включает широкое присутствие в американских акциях, международную диверсификацию и существенную долю облигаций. Коэффициент Шарпа за 3 года — 1,16.',
            bestFor_ru: 'Участники с 15–25 годами до выхода на пенсию, желающие роста с защитой от падения.',
            pros_ru: ['Устойчивый рост при умеренном риске: 17,71% годовая доходность за 3 года', 'Лучший коэффициент Шарпа среди моделей (1,16)', 'Очень низкий коэффициент расходов 0,10%', 'Ежеквартальная ребалансировка'],
            cons_ru: ['Умеренная волатильность (стандартное отклонение 10,44%)', 'Меньший потенциал роста, чем у агрессивной модели', 'Модельный портфель управляется планом']
        },

        modelBalanced: {
            id: 'modelBalanced',
            type: 'Model Portfolio',
            name: 'Murrieta Balanced Model',
            badge: 'Best Match',
            shortDesc: 'A balanced portfolio targeting 65% equity, 25% fixed income, and 10% stable value/cash for growth with meaningful stability.',
            riskLevel: 'Moderate',
            stockBond: '65% Equity / 25% Fixed / 10% SV/Cash',
            expenseRatio: '0.08%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants with 10-20 years to retirement seeking a balance of growth and stability.',
            performance: { yr1: '14.76%', yr3: '17.14%', yr5: '9.14%', yr10: '10.51%' },
            stats: { sharpe3yr: '1.27', stdDev3yr: '9.02%', inception: '9/1/2015', rebalance: 'Quarterly' },
            description: 'The Murrieta Balanced Model blends 65% equity, 25% fixed income, and 10% stable value/cash. It offers solid growth potential with meaningful downside protection. This model boasts the highest Sharpe ratio (1.27) among all four models, indicating the best risk-adjusted returns, and the lowest expense ratio at just 0.08%.',
            allocation: [
                '45.00% Vanguard Large Cap Index Admiral (VLCAX)',
                '15.00% Vanguard Interm-Term Bond Index Adm (VBILX)',
                '10.00% Vanguard Growth Index Admiral (VIGAX)',
                '10.00% Vanguard Treasury Money Market Investor (VUSXX)',
                '5.00% BlackRock High Yield K (BRHYX)',
                '5.00% Vanguard Inflation-Protected Secs Adm (VAIPX)',
                '5.00% Vanguard Total Intl Stock Index Admiral (VTIAX)',
                '3.00% iShares Russell Mid-Cap Index K (BRMKX)',
                '2.00% iShares Russell Small/Mid-Cap Idx K (BSMKX)'
            ],
            pros: ['Best risk-adjusted returns: Sharpe ratio of 1.27', 'Lowest expense ratio of all models at 0.08%', 'Stable value/cash allocation provides downside cushion', 'Quarterly rebalancing maintains target allocation'],
            cons: ['Lower growth potential than Moderate Growth and Aggressive models', 'Cash allocation may drag on returns in strong markets', 'Model portfolio is managed by the plan; participant selects it as a single option'],
            shortDesc_es: 'Una cartera balanceada con objetivo de 65% en renta variable, 25% en renta fija y 10% en valor estable/efectivo para crecimiento con estabilidad significativa.',
            description_es: 'El Modelo Balanceado de Murrieta combina 65% en renta variable, 25% en renta fija y 10% en valor estable/efectivo. Tiene el mayor ratio de Sharpe (1.27) entre todos los modelos y el ratio de gastos más bajo de 0.08%.',
            bestFor_es: 'Participantes con 10-20 años para jubilarse que buscan equilibrio entre crecimiento y estabilidad.',
            pros_es: ['Mejores rendimientos ajustados al riesgo: ratio de Sharpe de 1.27', 'Ratio de gastos más bajo de todos los modelos: 0.08%', 'La asignación en valor estable/efectivo amortigua las caídas', 'Rebalanceo trimestral mantiene la asignación objetivo'],
            cons_es: ['Menor potencial de crecimiento que los modelos Crecimiento Moderado y Agresivo', 'La asignación en efectivo puede restar rendimiento en mercados alcistas', 'La cartera modelo es gestionada por el plan'],
            shortDesc_zh: '以65%股票、25%固定收益和10%稳定价值/现金为目标的平衡投资组合，兼顾增长与稳定。',
            description_zh: '穆里埃塔平衡模型融合65%股票、25%固定收益和10%稳定价值/现金。在所有模型中夏普比率最高（1.27），费用率最低（0.08%）。',
            bestFor_zh: '距退休10-20年、寻求增长与稳定平衡的参与者。',
            pros_zh: ['最佳风险调整收益：夏普比率1.27', '所有模型中最低费用率0.08%', '稳定价值/现金配置提供下行缓冲', '季度再平衡维持目标配置'],
            cons_zh: ['增长潜力低于中度成长和激进模型', '现金配置在强势市场中可能拖累收益', '模型组合由计划管理'],
            shortDesc_ja: '株式65%・債券25%・安定価値/現金10%を目標とした、成長と安定を両立するバランス型ポートフォリオ。',
            description_ja: 'ムリエタバランスモデルは株式65%・債券25%・安定価値/現金10%を組み合わせます。全モデル中最高のシャープレシオ（1.27）と最低の経費率（0.08%）を誇ります。',
            bestFor_ja: '退職まで10〜20年あり、成長と安定のバランスを求める参加者。',
            pros_ja: ['最高のリスク調整後リターン：シャープレシオ1.27', '全モデル中最低の経費率0.08%', '安定価値/現金配分が下落に備える', '四半期リバランスで目標配分を維持'],
            cons_ja: ['中程度成長・積極型モデルより成長ポテンシャルが低い', '強い相場では現金配分がリターンを抑制する可能性', 'モデルポートフォリオはプランが管理'],
            shortDesc_tl: 'Isang balanseng portfolio na may target na 65% equity, 25% fixed income, at 10% stable value/cash para sa paglago na may makabuluhang katatagan.',
            description_tl: 'Pinagsasama ng Murrieta Balanced Model ang 65% equity, 25% fixed income, at 10% stable value/cash. Mayroon itong pinakamataas na Sharpe ratio (1.27) sa lahat ng modelo at pinakamababang expense ratio na 0.08%.',
            bestFor_tl: 'Mga kalahok na may 10-20 taon bago magretiro na naghahanap ng balanse ng paglago at katatagan.',
            pros_tl: ['Pinakamahusay na risk-adjusted returns: Sharpe ratio na 1.27', 'Pinakamababang expense ratio sa lahat ng modelo: 0.08%', 'Ang stable value/cash allocation ay nagbibigay ng cushion sa pagbaba', 'Quarterly rebalancing'],
            cons_tl: ['Mas mababang potensyal ng paglago kaysa sa Moderate Growth at Aggressive', 'Ang cash allocation ay maaaring makabawas sa returns sa malakas na merkado', 'Ang model portfolio ay pinamamahalaan ng plano'],
            shortDesc_pt: 'Uma carteira equilibrada com meta de 65% renda variável, 25% renda fixa e 10% valor estável/caixa para crescimento com estabilidade significativa.',
            description_pt: 'O Modelo Equilibrado de Murrieta combina 65% renda variável, 25% renda fixa e 10% valor estável/caixa. Tem o maior índice de Sharpe (1,27) e a menor taxa de despesas (0,08%) entre todos os modelos.',
            bestFor_pt: 'Participantes com 10-20 anos para a aposentadoria que buscam equilíbrio entre crescimento e estabilidade.',
            pros_pt: ['Melhores retornos ajustados ao risco: índice de Sharpe de 1,27', 'Menor taxa de despesas de todos os modelos: 0,08%', 'Alocação em valor estável/caixa oferece amortecimento', 'Rebalanceamento trimestral'],
            cons_pt: ['Menor potencial de crescimento que os modelos Crescimento Moderado e Agressivo', 'Alocação em caixa pode prejudicar retornos em mercados fortes', 'O portfólio modelo é gerenciado pelo plano'],
            shortDesc_fr: 'Un portefeuille équilibré ciblant 65 % actions, 25 % obligations et 10 % valeur stable/liquidités pour croissance et stabilité.',
            description_fr: 'Le Modèle Équilibré de Murrieta combine 65 % actions, 25 % obligations et 10 % valeur stable/liquidités. Il affiche le meilleur ratio de Sharpe (1,27) et le plus faible ratio de frais (0,08 %) parmi tous les modèles.',
            bestFor_fr: 'Participants avec 10 à 20 ans avant la retraite cherchant un équilibre entre croissance et stabilité.',
            pros_fr: ['Meilleurs rendements ajustés au risque : ratio de Sharpe de 1,27', 'Ratio de frais le plus bas de tous les modèles : 0,08 %', 'L\'allocation en valeur stable/liquidités amortit les baisses', 'Rééquilibrage trimestriel'],
            cons_fr: ['Potentiel de croissance inférieur aux modèles Croissance Modérée et Agressif', 'L\'allocation en liquidités peut peser sur les rendements en marchés haussiers', 'Le portefeuille modèle est géré par le plan'],
            shortDesc_de: 'Ein ausgewogenes Portfolio mit 65 % Aktien, 25 % Anleihen und 10 % Stable Value/Cash für Wachstum mit Stabilität.',
            description_de: 'Das Murrieta Balanced Modell kombiniert 65 % Aktien, 25 % Anleihen und 10 % Stable Value/Cash. Es hat die beste Sharpe Ratio (1,27) und die niedrigste Kostenquote (0,08 %) aller Modelle.',
            bestFor_de: 'Teilnehmer mit 10–20 Jahren bis zur Rente, die Wachstum und Stabilität ausbalancieren möchten.',
            pros_de: ['Beste risikobereinigte Rendite: Sharpe Ratio 1,27', 'Niedrigste Kostenquote aller Modelle: 0,08 %', 'Stable Value/Cash-Anteil dämpft Verluste', 'Vierteljährliche Neugewichtung'],
            cons_de: ['Geringeres Wachstumspotenzial als Moderate Growth und Aggressive', 'Cash-Anteil kann in starken Märkten die Rendite belasten', 'Modellportfolio wird vom Plan verwaltet'],
            shortDesc_ru: 'Сбалансированный портфель с целью 65% акции / 25% облигации / 10% стабильная стоимость/наличные для роста со значительной стабильностью.',
            description_ru: 'Сбалансированная модель Мурриета объединяет 65% акций, 25% облигаций и 10% стабильной стоимости/наличных. Лучший коэффициент Шарпа (1,27) и самый низкий коэффициент расходов (0,08%) среди всех моделей.',
            bestFor_ru: 'Участники с 10–20 годами до пенсии, ищущие баланс между ростом и стабильностью.',
            pros_ru: ['Лучшие скорректированные на риск доходы: коэффициент Шарпа 1,27', 'Самый низкий коэффициент расходов среди всех моделей: 0,08%', 'Доля стабильной стоимости/наличных смягчает падения', 'Ежеквартальная ребалансировка'],
            cons_ru: ['Меньший потенциал роста, чем у моделей умеренного роста и агрессивной', 'Доля наличных может снижать доходность на растущих рынках', 'Модельный портфель управляется планом']
        },

        modelConservative: {
            id: 'modelConservative',
            type: 'Model Portfolio',
            name: 'Murrieta Conservative Model',
            badge: 'Best Match',
            shortDesc: 'A stability-focused portfolio targeting 45% equity, 40% fixed income, and 15% stable value/cash, emphasizing capital preservation.',
            riskLevel: 'Conservative',
            stockBond: '45% Equity / 40% Fixed / 15% SV/Cash',
            expenseRatio: '0.10%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants nearing retirement or who prioritize capital preservation and income.',
            performance: { yr1: '12.47%', yr3: '13.16%', yr5: '6.74%', yr10: '8.17%' },
            stats: { sharpe3yr: '1.09', stdDev3yr: '7.15%', inception: '9/1/2015', rebalance: 'Quarterly' },
            description: 'The Murrieta Conservative Model targets 45% equity, 40% fixed income, and 15% stable value/cash. It is designed for participants approaching or in retirement who prioritize stability and income. The significant bond and stable value allocation provides a meaningful cushion against market downturns while still offering growth through its equity holdings.',
            allocation: [
                '30.00% Vanguard Large Cap Index Admiral (VLCAX)',
                '20.00% Vanguard Interm-Term Bond Index Adm (VBILX)',
                '15.00% Vanguard Treasury Money Market Investor (VUSXX)',
                '10.00% Vanguard Inflation-Protected Secs Adm (VAIPX)',
                '5.00% BlackRock High Yield K (BRHYX)',
                '5.00% Vanguard Growth Index Admiral (VIGAX)',
                '5.00% Vanguard Multi-Sector Income Bond Adm',
                '5.00% Vanguard Total Intl Stock Index Admiral (VTIAX)',
                '3.00% iShares Russell Mid-Cap Index K (BRMKX)',
                '2.00% iShares Russell Small/Mid-Cap Idx K (BSMKX)'
            ],
            pros: ['Lowest volatility of all models (7.15% standard deviation)', 'Significant stable value and bond allocation for capital preservation', '15% money market provides liquidity and safety', 'Quarterly rebalancing maintains target allocation'],
            cons: ['Lowest growth potential among the four models', 'May not keep pace with inflation in low-rate environments', 'Model portfolio is managed by the plan; participant selects it as a single option'],
            shortDesc_es: 'Una cartera enfocada en la estabilidad con objetivo de 45% en renta variable, 40% en renta fija y 15% en valor estable/efectivo, priorizando la preservación de capital.',
            description_es: 'El Modelo Conservador de Murrieta tiene como objetivo un 45% en renta variable, un 40% en renta fija y un 15% en valor estable/efectivo. Diseñado para participantes próximos a la jubilación que priorizan la estabilidad y los ingresos. La asignación en bonos y valor estable proporciona protección contra las caídas del mercado.',
            bestFor_es: 'Participantes próximos a la jubilación o que priorizan la preservación de capital y los ingresos.',
            pros_es: ['Menor volatilidad de todos los modelos (desviación estándar de 7.15%)', 'Asignación importante en valor estable y bonos para preservar capital', '15% en mercado monetario aporta liquidez y seguridad', 'Rebalanceo trimestral mantiene la asignación objetivo'],
            cons_es: ['Menor potencial de crecimiento entre los cuatro modelos', 'Puede no mantenerse al ritmo de la inflación en entornos de tasas bajas', 'La cartera modelo es gestionada por el plan'],
            shortDesc_zh: '以45%股票、40%固定收益和15%稳定价值/现金为目标的稳健投资组合，优先保全资本。',
            description_zh: '穆里埃塔保守模型目标为45%股票、40%固定收益和15%稳定价值/现金。专为临近退休、优先考虑稳定和收入的参与者设计。债券和稳定价值配置为市场下行提供缓冲。',
            bestFor_zh: '临近退休或优先考虑资本保全和收益的参与者。',
            pros_zh: ['所有模型中波动性最低（标准差7.15%）', '大量稳定价值和债券配置用于资本保全', '15%货币市场提供流动性和安全性', '季度再平衡维持目标配置'],
            cons_zh: ['四个模型中增长潜力最低', '低利率环境下可能跟不上通货膨胀', '模型组合由计划管理'],
            shortDesc_ja: '株式45%・債券40%・安定価値/現金15%を目標とした、資本保全を重視する安定志向ポートフォリオ。',
            description_ja: 'ムリエタ保守モデルは株式45%・債券40%・安定価値/現金15%を目標とします。退職近くで安定と収益を重視する参加者向けです。債券と安定価値配分が市場の下落から守ります。',
            bestFor_ja: '退職が近く、資本保全と収益を優先する参加者。',
            pros_ja: ['全モデル中最低のボラティリティ（標準偏差7.15%）', '資本保全のための大きな安定価値・債券配分', '15%マネーマーケットが流動性と安全性を提供', '四半期リバランス'],
            cons_ja: ['4モデル中最低の成長ポテンシャル', '低金利環境ではインフレに追いつかない可能性', 'モデルポートフォリオはプランが管理'],
            shortDesc_tl: 'Isang portfolio na nakatuon sa katatagan na may target na 45% equity, 40% fixed income, at 15% stable value/cash, na inuuna ang pangangalaga ng kapital.',
            description_tl: 'Ang Murrieta Conservative Model ay nagta-target ng 45% equity, 40% fixed income, at 15% stable value/cash. Dinisenyo para sa mga kalahok na malapit nang magretiro na inuuna ang katatagan at kita. Ang bond at stable value allocation ay nagbibigay ng proteksyon laban sa pagbaba ng merkado.',
            bestFor_tl: 'Mga kalahok na malapit nang magretiro o inuuna ang pangangalaga ng kapital at kita.',
            pros_tl: ['Pinakamababang volatility sa lahat ng modelo (7.15% standard deviation)', 'Makabuluhang stable value at bond allocation para sa pangangalaga ng kapital', '15% money market ay nagbibigay ng liquidity at kaligtasan', 'Quarterly rebalancing'],
            cons_tl: ['Pinakamababang potensyal ng paglago sa apat na modelo', 'Maaaring hindi makaagapay sa inflation sa mababang rate na kapaligiran', 'Ang model portfolio ay pinamamahalaan ng plano'],
            shortDesc_pt: 'Uma carteira focada em estabilidade com meta de 45% renda variável, 40% renda fixa e 15% valor estável/caixa, priorizando a preservação de capital.',
            description_pt: 'O Modelo Conservador de Murrieta tem como meta 45% renda variável, 40% renda fixa e 15% valor estável/caixa. Projetado para participantes próximos à aposentadoria que priorizam estabilidade e renda.',
            bestFor_pt: 'Participantes próximos à aposentadoria ou que priorizam a preservação de capital e renda.',
            pros_pt: ['Menor volatilidade de todos os modelos (desvio padrão de 7,15%)', 'Alocação significativa em valor estável e títulos para preservação de capital', '15% em mercado monetário fornece liquidez e segurança', 'Rebalanceamento trimestral'],
            cons_pt: ['Menor potencial de crescimento entre os quatro modelos', 'Pode não acompanhar a inflação em ambientes de taxas baixas', 'O portfólio modelo é gerenciado pelo plano'],
            shortDesc_fr: 'Un portefeuille axé sur la stabilité ciblant 45 % actions, 40 % obligations et 15 % valeur stable/liquidités, avec priorité à la préservation du capital.',
            description_fr: 'Le Modèle Conservateur de Murrieta cible 45 % actions, 40 % obligations et 15 % valeur stable/liquidités. Conçu pour les participants proches de la retraite qui privilégient la stabilité et le revenu.',
            bestFor_fr: 'Participants proches de la retraite ou privilégiant la préservation du capital et le revenu.',
            pros_fr: ['Volatilité la plus faible de tous les modèles (écart-type de 7,15 %)', 'Allocation significative en valeur stable et obligations pour préserver le capital', '15 % en marché monétaire fournit liquidité et sécurité', 'Rééquilibrage trimestriel'],
            cons_fr: ['Potentiel de croissance le plus faible des quatre modèles', 'Peut ne pas suivre l\'inflation en environnement de taux bas', 'Le portefeuille modèle est géré par le plan'],
            shortDesc_de: 'Ein stabilitätsorientiertes Portfolio mit 45 % Aktien, 40 % Anleihen und 15 % Stable Value/Cash mit Fokus auf Kapitalerhalt.',
            description_de: 'Das Murrieta Conservative Modell zielt auf 45 % Aktien, 40 % Anleihen und 15 % Stable Value/Cash. Konzipiert für Teilnehmer nahe der Rente, die Stabilität und Erträge bevorzugen.',
            bestFor_de: 'Teilnehmer kurz vor der Rente oder mit Fokus auf Kapitalerhalt und Erträge.',
            pros_de: ['Geringste Volatilität aller Modelle (Standardabweichung 7,15 %)', 'Erheblicher Stable Value- und Anleihenanteil für Kapitalerhalt', '15 % Geldmarkt bietet Liquidität und Sicherheit', 'Vierteljährliche Neugewichtung'],
            cons_de: ['Geringstes Wachstumspotenzial der vier Modelle', 'Möglicherweise keine Inflationsabsicherung bei Niedrigzinsen', 'Modellportfolio wird vom Plan verwaltet'],
            shortDesc_ru: 'Портфель, ориентированный на стабильность, с целевым распределением 45% акции / 40% облигации / 15% стабильная стоимость/наличные, приоритет — сохранение капитала.',
            description_ru: 'Консервативная модель Мурриета нацелена на 45% акций, 40% облигаций и 15% стабильной стоимости/наличных. Разработана для участников, близких к пенсии, которые ценят стабильность и доход.',
            bestFor_ru: 'Участники, близкие к выходу на пенсию, или те, кто ставит во главу угла сохранение капитала и доход.',
            pros_ru: ['Наименьшая волатильность среди всех моделей (стандартное отклонение 7,15%)', 'Значительная доля стабильной стоимости и облигаций для сохранения капитала', '15% денежного рынка обеспечивает ликвидность и безопасность', 'Ежеквартальная ребалансировка'],
            cons_ru: ['Наименьший потенциал роста среди четырёх моделей', 'В условиях низких ставок может не успевать за инфляцией', 'Модельный портфель управляется планом']
        },

        // ── Target Date Fund (dynamic — do not remove) ─────────
        targetDate: {
            id: 'targetDate',
            type: 'Target Date Fund',
            name: '',           // Set dynamically
            badge: '',
            shortDesc: 'A Vanguard Target Retirement Fund that automatically adjusts its stock/bond mix to become more conservative as you approach your target retirement year.',
            riskLevel: '',      // Set dynamically
            stockBond: '',      // Set dynamically
            expenseRatio: '0.08%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants who want a professionally managed, hands-off approach to retirement investing.',
            description: 'Vanguard Target Retirement Funds are all-in-one solutions available in the City of Murrieta plan. You choose the fund closest to your expected retirement year, and Vanguard automatically adjusts the asset allocation over time through a "glide path." The fund invests in a mix of Vanguard mutual funds, shifting from stocks to bonds as retirement approaches. These funds are among the most popular options in the plan.',
            allocation: [],     // Set dynamically
            pros: ['Fully automatic rebalancing and glide path', 'Simple one-fund solution requiring no maintenance', 'Very low expense ratio of 0.08%', 'Vanguard Target Retirement Funds are the largest target date series in the U.S.'],
            cons: ['Less control over individual holdings', 'One-size-fits-all approach may not suit everyone', 'Fixed glide path does not account for individual circumstances'],
            shortDesc_es: 'Un Fondo de Fecha Objetivo de Vanguard que ajusta automáticamente su combinación de acciones/bonos para ser más conservador a medida que se acerca su año objetivo de jubilación.',
            description_es: 'Los Fondos de Jubilación Objetivo de Vanguard son soluciones integrales disponibles en el plan de la Ciudad de Murrieta. Usted elige el fondo más cercano a su año esperado de jubilación y Vanguard ajusta automáticamente la asignación a lo largo del tiempo mediante una trayectoria de planeo. Estos fondos son de las opciones más populares del plan.',
            bestFor_es: 'Participantes que desean un enfoque de inversión profesional y sin complicaciones para la jubilación.',
            pros_es: ['Rebalanceo totalmente automático y trayectoria de planeo', 'Solución simple de un solo fondo sin mantenimiento', 'Muy bajo ratio de gastos de 0.08%', 'Los Fondos Objetivo de Vanguard son la serie más grande de EE.UU.'],
            cons_es: ['Menos control sobre las posiciones individuales', 'El enfoque único puede no adaptarse a todos', 'La trayectoria fija no considera las circunstancias individuales'],
            shortDesc_zh: 'Vanguard目标日期基金，随着您临近目标退休年份，自动调整股票/债券组合，变得更加保守。',
            description_zh: 'Vanguard目标退休基金是穆里埃塔市计划中的一体化解决方案。您选择最接近预期退休年份的基金，Vanguard会随时间通过"下滑轨道"自动调整资产配置。这些基金是计划中最受欢迎的选择之一。',
            bestFor_zh: '希望以专业管理、轻松方式进行退休投资的参与者。',
            pros_zh: ['完全自动的再平衡和下滑轨道', '简单的单基金解决方案，无需维护', '极低费用率0.08%', 'Vanguard目标退休基金是美国最大的目标日期基金系列'],
            cons_zh: ['对个人持仓控制较少', '一刀切的方式可能不适合所有人', '固定下滑轨道不考虑个人情况'],
            shortDesc_ja: 'Vanguardターゲット・リタイアメント・ファンドは、目標退職年に近づくにつれて株式・債券の比率を自動的に保守的に調整します。',
            description_ja: 'Vanguardターゲット・リタイアメント・ファンドは、ムリエタ市プランで利用できるオールインワンソリューションです。退職予定年に最も近いファンドを選ぶと、Vanguardが「グライドパス」を通じて自動的に資産配分を調整します。',
            bestFor_ja: 'プロが管理する、手間のかからない退職投資アプローチを望む参加者。',
            pros_ja: ['完全自動のリバランスとグライドパス', 'メンテナンス不要のシンプルな1ファンド解決策', '非常に低い経費率0.08%', 'VanguardターゲットファンドはUS最大のシリーズ'],
            cons_ja: ['個別保有銘柄への管理が少ない', '画一的なアプローチが全員に合わないことがある', '固定グライドパスは個人の事情を考慮しない'],
            shortDesc_tl: 'Isang Vanguard Target Date Fund na awtomatikong inaayos ang halo ng stocks/bonds nito upang maging mas konserbatibo habang papalapit ang iyong target na taon ng pagreretiro.',
            description_tl: 'Ang mga Vanguard Target Retirement Fund ay all-in-one na solusyon sa City of Murrieta plan. Pipiliin mo ang pondo na pinakamalapit sa iyong inaasahang taon ng pagreretiro, at awtomatikong ia-adjust ng Vanguard ang asset allocation sa paglipas ng panahon.',
            bestFor_tl: 'Mga kalahok na nagnanais ng propesyonal na pamamahala at walang abalang diskarte sa pamumuhunan para sa pagreretiro.',
            pros_tl: ['Ganap na awtomatikong rebalancing at glide path', 'Simple na solusyong isang pondo na hindi nangangailangan ng maintenance', 'Napakababang expense ratio na 0.08%', 'Ang Vanguard Target Retirement Funds ang pinakamalaking series sa U.S.'],
            cons_tl: ['Mas kaunting kontrol sa mga indibidwal na holdings', 'Ang one-size-fits-all na diskarte ay maaaring hindi angkop sa lahat', 'Ang fixed glide path ay hindi isinasaalang-alang ang mga indibidwal na pangyayari'],
            shortDesc_pt: 'Um Fundo com Data-Alvo da Vanguard que ajusta automaticamente sua combinação de ações/títulos para ser mais conservador conforme se aproxima do ano-alvo de aposentadoria.',
            description_pt: 'Os Fundos Vanguard Target Retirement são soluções completas disponíveis no plano da Cidade de Murrieta. Você escolhe o fundo mais próximo do seu ano de aposentadoria e a Vanguard ajusta automaticamente a alocação ao longo do tempo através de uma trajetória de deslizamento.',
            bestFor_pt: 'Participantes que desejam uma abordagem gerenciada profissionalmente e sem complicações para investir para a aposentadoria.',
            pros_pt: ['Rebalanceamento totalmente automático e trajetória de deslizamento', 'Solução simples de um único fundo sem manutenção', 'Taxa de despesas muito baixa de 0,08%', 'Os Fundos Target Retirement da Vanguard são a maior série de fundos com data-alvo nos EUA'],
            cons_pt: ['Menos controle sobre posições individuais', 'Abordagem única pode não servir para todos', 'Trajetória fixa não considera circunstâncias individuais'],
            shortDesc_fr: 'Un Fonds à Date Cible Vanguard qui ajuste automatiquement son mix actions/obligations pour devenir plus conservateur à l\'approche de l\'année cible de retraite.',
            description_fr: 'Les Fonds Vanguard Target Retirement sont des solutions tout-en-un disponibles dans le plan de la Ville de Murrieta. Vous choisissez le fonds le plus proche de votre année de retraite prévue et Vanguard ajuste automatiquement l\'allocation au fil du temps.',
            bestFor_fr: 'Participants souhaitant une approche d\'investissement gérée professionnellement et sans contrainte pour la retraite.',
            pros_fr: ['Rééquilibrage entièrement automatique et trajectoire de glisse', 'Solution simple à un seul fonds sans maintenance', 'Très faible ratio de frais de 0,08 %', 'Les fonds Vanguard Target Retirement sont la plus grande série aux États-Unis'],
            cons_fr: ['Moins de contrôle sur les positions individuelles', 'L\'approche universelle peut ne pas convenir à tous', 'La trajectoire fixe ne tient pas compte des circonstances individuelles'],
            shortDesc_de: 'Ein Vanguard-Zieldatumsfonds, der seine Aktien-/Anleihenaufteilung automatisch anpasst, um konservativer zu werden, je näher das Renteneintrittsjahr rückt.',
            description_de: 'Vanguard Target Retirement Fonds sind All-in-One-Lösungen im Stadtplan. Sie wählen den Fonds, der Ihrem Renteneintrittsalter am nächsten liegt, und Vanguard passt die Vermögensaufteilung automatisch über einen Gleitpfad an.',
            bestFor_de: 'Teilnehmer, die eine professionell verwaltete, unkomplizierte Altersvorsorgelösung wünschen.',
            pros_de: ['Vollautomatisches Rebalancing und Gleitpfad', 'Einfache Ein-Fonds-Lösung ohne Wartung', 'Sehr niedrige Kostenquote von 0,08 %', 'Vanguard Target Retirement Fonds sind die größte Zieldatumsserie in den USA'],
            cons_de: ['Weniger Kontrolle über einzelne Positionen', 'Einheitslösung passt möglicherweise nicht für alle', 'Fester Gleitpfad berücksichtigt keine individuellen Umstände'],
            shortDesc_ru: 'Фонд с целевой датой Vanguard, автоматически корректирующий соотношение акций/облигаций, становясь более консервативным по мере приближения целевого года выхода на пенсию.',
            description_ru: 'Фонды Vanguard Target Retirement — комплексные решения в городском плане. Вы выбираете фонд, ближайший к вашему предполагаемому году выхода на пенсию, а Vanguard автоматически корректирует распределение активов через «скользящий путь».',
            bestFor_ru: 'Участники, желающие профессионально управляемого, не требующего усилий подхода к пенсионным инвестициям.',
            pros_ru: ['Полностью автоматическая ребалансировка и скользящий путь', 'Простое решение с одним фондом без обслуживания', 'Очень низкий коэффициент расходов 0,08%', 'Фонды Vanguard Target Retirement — крупнейшая серия в США'],
            cons_ru: ['Меньше контроля над отдельными позициями', 'Единый подход может не подойти всем', 'Фиксированный скользящий путь не учитывает индивидуальные обстоятельства']
        },

        // ── Allocation Funds ───────────────────────────────────
        lifestrategyGrowth: {
            id: 'lifestrategyGrowth',
            type: 'Allocation Fund',
            name: 'Vanguard LifeStrategy Growth Fund (VASGX)',
            badge: '',
            shortDesc: 'Invests in a mix of Vanguard funds with approximately 80% in stocks and 20% in bonds, seeking capital appreciation and some current income.',
            riskLevel: 'Moderately Aggressive',
            stockBond: '80% Stocks / 20% Bonds',
            expenseRatio: '0.12%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants with a long time horizon who want a growth-oriented, hands-off solution with a fixed allocation.',
            performance: { yr1: '21.81%', yr3: '17.36%', yr5: '9.26%', yr10: '10.94%' },
            description: 'The Vanguard LifeStrategy Growth Fund invests in a mix of Vanguard mutual funds with approximately 80% allocated to stocks and 20% to bonds. The fund provides broad exposure to U.S. and international equity and fixed-income markets. Unlike a target date fund, this allocation remains fixed and does not become more conservative over time, making it ideal for investors who are comfortable maintaining a growth-oriented profile throughout their investment horizon.',
            allocation: [
                '~48% Vanguard Total Stock Market Index',
                '~32% Vanguard Total International Stock Index',
                '~14% Vanguard Total Bond Market II Index',
                '~6% Vanguard Total International Bond II Index'
            ],
            pros: ['Strong long-term growth potential with 80% equity allocation', 'Very low expense ratio of 0.12%', 'Broad global diversification across U.S. and international markets', 'Automatic rebalancing within the fund'],
            cons: ['Fixed allocation does not become more conservative over time', 'Higher volatility than moderate or conservative options', 'No stable value, TIPS, or real estate component'],
            shortDesc_es: 'Invierte en una combinación de fondos Vanguard con aproximadamente 80% en acciones y 20% en bonos, buscando apreciación de capital y algunos ingresos actuales.',
            description_es: 'El Fondo Vanguard LifeStrategy Growth invierte aproximadamente un 80% en acciones y un 20% en bonos. Ofrece amplia exposición a los mercados de renta variable y fija de EE.UU. e internacionales. A diferencia de un fondo de fecha objetivo, esta asignación es fija y no se vuelve más conservadora con el tiempo.',
            bestFor_es: 'Participantes con horizonte largo que desean una solución orientada al crecimiento con asignación fija.',
            pros_es: ['Sólido potencial de crecimiento a largo plazo con 80% en renta variable', 'Muy bajo ratio de gastos de 0.12%', 'Amplia diversificación global', 'Rebalanceo automático dentro del fondo'],
            cons_es: ['La asignación fija no se vuelve más conservadora con el tiempo', 'Mayor volatilidad que las opciones moderadas o conservadoras', 'Sin componente de valor estable, TIPS o bienes raíces'],
            shortDesc_zh: '投资于约80%股票和20%债券的Vanguard基金组合，追求资本增值和一定的当期收入。',
            description_zh: 'Vanguard LifeStrategy成长基金投资约80%股票和20%债券，提供美国和国际股票及固定收益市场的广泛敞口。与目标日期基金不同，这种配置是固定的，不会随时间变得更保守。',
            bestFor_zh: '投资期限较长、希望以固定配置保持成长导向的参与者。',
            pros_zh: ['80%股票配置带来强劲长期增长潜力', '极低费用率0.12%', '广泛的全球分散投资', '基金内部自动再平衡'],
            cons_zh: ['固定配置不会随时间变得更保守', '比中等或保守选项波动性更高', '无稳定价值、通胀保值债券或房地产成分'],
            shortDesc_ja: 'Vanguardファンドの組み合わせに約80%株式・20%債券で投資し、キャピタルゲインと一定の収益を目指します。',
            description_ja: 'Vanguard LifeStrategy成長ファンドは約80%を株式・20%を債券に配分します。米国・海外の株式・債券市場に幅広く投資します。ターゲットデートファンドと異なり、配分は固定で時間とともに保守的になりません。',
            bestFor_ja: '長期投資期間を持ち、固定配分の成長志向ソリューションを望む参加者。',
            pros_ja: ['80%株式配分による強い長期成長ポテンシャル', '非常に低い経費率0.12%', '米国・海外市場にわたる広い分散投資', 'ファンド内自動リバランス'],
            cons_ja: ['固定配分は時間とともに保守的にならない', '中程度・保守的な選択肢より高いボラティリティ', '安定価値・TIPS・不動産成分なし'],
            shortDesc_tl: 'Namumuhunan sa halo ng mga Vanguard fund na may humigit-kumulang 80% sa stocks at 20% sa bonds, naghahanap ng pagpapalaki ng kapital at ilang kasalukuyang kita.',
            description_tl: 'Ang Vanguard LifeStrategy Growth Fund ay namumuhunan ng humigit-kumulang 80% sa stocks at 20% sa bonds. Nagbibigay ng malawak na exposure sa U.S. at internasyonal na equity at fixed-income markets. Hindi tulad ng target date fund, ang allocation na ito ay nanatiling fixed.',
            bestFor_tl: 'Mga kalahok na may mahabang time horizon na nagnanais ng growth-oriented na solusyon na may fixed allocation.',
            pros_tl: ['Matibay na pangmatagalang potensyal ng paglago na may 80% equity allocation', 'Napakababang expense ratio na 0.12%', 'Malawak na pandaigdigang diversification', 'Awtomatikong rebalancing sa loob ng pondo'],
            cons_tl: ['Ang fixed allocation ay hindi nagiging mas konserbatibo sa paglipas ng panahon', 'Mas mataas na volatility kaysa sa katamtaman o konserbatibong mga opsyon', 'Walang stable value, TIPS, o real estate component'],
            shortDesc_pt: 'Investe em uma combinação de fundos Vanguard com aproximadamente 80% em ações e 20% em títulos, buscando valorização de capital e alguma renda atual.',
            description_pt: 'O Fundo Vanguard LifeStrategy Growth investe aproximadamente 80% em ações e 20% em títulos. Oferece ampla exposição aos mercados de renda variável e fixa dos EUA e internacionais. Diferente de um fundo com data-alvo, esta alocação é fixa e não se torna mais conservadora ao longo do tempo.',
            bestFor_pt: 'Participantes com longo horizonte de tempo que desejam uma solução orientada ao crescimento com alocação fixa.',
            pros_pt: ['Forte potencial de crescimento a longo prazo com 80% em renda variável', 'Taxa de despesas muito baixa de 0,12%', 'Ampla diversificação global', 'Rebalanceamento automático dentro do fundo'],
            cons_pt: ['Alocação fixa não se torna mais conservadora com o tempo', 'Maior volatilidade do que opções moderadas ou conservadoras', 'Sem componente de valor estável, TIPS ou imóveis'],
            shortDesc_fr: 'Investit dans un mix de fonds Vanguard avec environ 80 % en actions et 20 % en obligations, cherchant une appréciation du capital et un certain revenu actuel.',
            description_fr: 'Le Fonds Vanguard LifeStrategy Growth investit environ 80 % en actions et 20 % en obligations. Il offre une large exposition aux marchés actions et obligataires américains et internationaux. Contrairement à un fonds à date cible, cette allocation est fixe et ne devient pas plus conservatrice avec le temps.',
            bestFor_fr: 'Participants avec un long horizon d\'investissement souhaitant une solution orientée croissance avec une allocation fixe.',
            pros_fr: ['Fort potentiel de croissance à long terme avec 80 % en actions', 'Très faible ratio de frais de 0,12 %', 'Large diversification mondiale', 'Rééquilibrage automatique au sein du fonds'],
            cons_fr: ['L\'allocation fixe ne devient pas plus conservatrice avec le temps', 'Volatilité plus élevée que les options modérées ou conservatrices', 'Pas de composante valeur stable, TIPS ou immobilier'],
            shortDesc_de: 'Investiert in einen Mix aus Vanguard-Fonds mit ca. 80 % Aktien und 20 % Anleihen für Kapitalwachstum und laufende Erträge.',
            description_de: 'Der Vanguard LifeStrategy Growth Fund investiert ca. 80 % in Aktien und 20 % in Anleihen. Er bietet breite Exposition in US- und internationalen Aktien- und Anleihemärkten. Im Gegensatz zu Zieldatumsfonds bleibt die Aufteilung konstant und wird nicht konservativer.',
            bestFor_de: 'Teilnehmer mit langem Anlagehorizont, die eine wachstumsorientierte Lösung mit fester Aufteilung bevorzugen.',
            pros_de: ['Starkes langfristiges Wachstumspotenzial mit 80 % Aktien', 'Sehr niedrige Kostenquote von 0,12 %', 'Breite globale Diversifikation', 'Automatisches Rebalancing im Fonds'],
            cons_de: ['Feste Aufteilung wird nicht konservativer', 'Höhere Volatilität als moderate oder konservative Optionen', 'Kein Stable Value-, TIPS- oder Immobilienanteil'],
            shortDesc_ru: 'Инвестирует в сочетание фондов Vanguard примерно с 80% акций и 20% облигаций, нацелено на прирост капитала и текущий доход.',
            description_ru: 'Фонд Vanguard LifeStrategy Growth инвестирует около 80% в акции и 20% в облигации. Обеспечивает широкую экспозицию на американские и международные рынки. В отличие от фондов с целевой датой, распределение фиксировано и не становится более консервативным.',
            bestFor_ru: 'Участники с долгосрочным горизонтом, желающие ориентированного на рост решения с фиксированным распределением.',
            pros_ru: ['Сильный долгосрочный потенциал роста при 80% акций', 'Очень низкий коэффициент расходов 0,12%', 'Широкая глобальная диверсификация', 'Автоматическая ребалансировка внутри фонда'],
            cons_ru: ['Фиксированное распределение не становится более консервативным', 'Более высокая волатильность, чем у умеренных или консервативных вариантов', 'Нет компонентов стабильной стоимости, TIPS или недвижимости']
        },

        lifestrategyConservative: {
            id: 'lifestrategyConservative',
            type: 'Allocation Fund',
            name: 'Vanguard LifeStrategy Conservative Growth Fund (VSCGX)',
            badge: '',
            shortDesc: 'Invests in a mix of Vanguard funds with approximately 40% in stocks and 60% in bonds, seeking current income and low to moderate capital appreciation.',
            riskLevel: 'Conservative',
            stockBond: '40% Stocks / 60% Bonds',
            expenseRatio: '0.12%',
            turnover: 'Low',
            minInvestment: 'None',
            bestFor: 'Participants nearing retirement or with a low risk tolerance who still want some growth exposure.',
            performance: { yr1: '13.58%', yr3: '11.19%', yr5: '4.84%', yr10: '6.45%' },
            description: 'The Vanguard LifeStrategy Conservative Growth Fund invests in a mix of Vanguard mutual funds according to an asset-allocation strategy that reflects approximately 60% fixed-income securities and 40% common stocks. The indirect fixed-income holdings include a diversified mix of short-, intermediate-, and long-term U.S. government, agency, and investment-grade corporate bonds, as well as international bonds. This conservative allocation provides stability and income while maintaining some equity exposure to help offset inflation.',
            allocation: [
                '~24% Vanguard Total Stock Market Index',
                '~16% Vanguard Total International Stock Index',
                '~42% Vanguard Total Bond Market II Index',
                '~18% Vanguard Total International Bond II Index'
            ],
            pros: ['Low volatility with meaningful bond allocation', 'Broad global diversification for a conservative fund', 'Very low expense ratio of 0.12%', 'Automatic rebalancing within the fund'],
            cons: ['Fixed allocation does not adjust with age', 'Limited upside in strong equity markets', 'May not provide enough growth for younger investors'],
            shortDesc_es: 'Invierte en una combinación de fondos Vanguard con aproximadamente 40% en acciones y 60% en bonos, buscando ingresos actuales y apreciación de capital de baja a moderada.',
            description_es: 'El Fondo Vanguard LifeStrategy Conservative Growth invierte aproximadamente un 60% en renta fija y un 40% en acciones. La asignación en renta fija incluye bonos diversificados de EE.UU. e internacionales. Esta asignación conservadora proporciona estabilidad e ingresos manteniendo cierta exposición a la renta variable.',
            bestFor_es: 'Participantes próximos a la jubilación o con baja tolerancia al riesgo que aún desean cierta exposición al crecimiento.',
            pros_es: ['Baja volatilidad con importante asignación en bonos', 'Amplia diversificación global para un fondo conservador', 'Muy bajo ratio de gastos de 0.12%', 'Rebalanceo automático dentro del fondo'],
            cons_es: ['La asignación fija no se ajusta con la edad', 'Potencial alcista limitado en mercados fuertes', 'Puede no proporcionar suficiente crecimiento para inversores jóvenes'],
            shortDesc_zh: '投资于约40%股票和60%债券的Vanguard基金组合，追求当期收入和低至中等的资本增值。',
            description_zh: 'Vanguard LifeStrategy保守成长基金按照约60%固定收益、40%股票的策略投资。固定收益部分包括多样化的美国和国际债券。这种保守配置在提供稳定性和收入的同时保持一定的股票敞口。',
            bestFor_zh: '临近退休或风险承受能力低但仍希望一定增长敞口的参与者。',
            pros_zh: ['低波动性，债券配置占比高', '对保守型基金而言具有广泛全球分散投资', '极低费用率0.12%', '基金内部自动再平衡'],
            cons_zh: ['固定配置不随年龄调整', '强劲股票市场中上行空间有限', '对年轻投资者可能增长不足'],
            shortDesc_ja: 'Vanguardファンドの組み合わせに約40%株式・60%債券で投資し、安定収益と低〜中程度の値上がりを目指します。',
            description_ja: 'Vanguard LifeStrategy保守成長ファンドは約60%固定収益・40%株式で運用します。固定収益部分は国内外の多様な債券を含みます。保守的な配分で安定性と収益を提供しながら、一定の株式エクスポージャーを維持します。',
            bestFor_ja: '退職が近い、またはリスク許容度が低くも一定の成長を望む参加者。',
            pros_ja: ['重要な債券配分による低ボラティリティ', '保守的なファンドとして広い世界分散投資', '非常に低い経費率0.12%', 'ファンド内自動リバランス'],
            cons_ja: ['固定配分は年齢とともに調整されない', '強い株式相場でのアップサイドが限られる', '若い投資家には十分な成長をもたらさない可能性'],
            shortDesc_tl: 'Namumuhunan sa halo ng mga Vanguard fund na may humigit-kumulang 40% sa stocks at 60% sa bonds, naghahanap ng kasalukuyang kita at mababa hanggang katamtamang pagpapalaki ng kapital.',
            description_tl: 'Ang Vanguard LifeStrategy Conservative Growth Fund ay namumuhunan ayon sa isang asset-allocation na estratehiya na humigit-kumulang 60% fixed-income at 40% stocks. Ang conservative allocation na ito ay nagbibigay ng katatagan at kita habang pinapanatili ang ilang equity exposure.',
            bestFor_tl: 'Mga kalahok na malapit nang magretiro o may mababang toleransya sa panganib na nais pa ring may ilang exposure sa paglago.',
            pros_tl: ['Mababang volatility na may makabuluhang bond allocation', 'Malawak na pandaigdigang diversification para sa conservative na pondo', 'Napakababang expense ratio na 0.12%', 'Awtomatikong rebalancing sa loob ng pondo'],
            cons_tl: ['Ang fixed allocation ay hindi nag-a-adjust sa edad', 'Limitadong upside sa malakas na equity markets', 'Maaaring hindi magbigay ng sapat na paglago para sa mas batang mga mamumuhunan'],
            shortDesc_pt: 'Investe em uma combinação de fundos Vanguard com aproximadamente 40% em ações e 60% em títulos, buscando renda atual e valorização de capital de baixa a moderada.',
            description_pt: 'O Fundo Vanguard LifeStrategy Conservative Growth investe seguindo uma estratégia de cerca de 60% renda fixa e 40% ações. A alocação conservadora oferece estabilidade e renda, mantendo alguma exposição ao mercado de ações.',
            bestFor_pt: 'Participantes próximos à aposentadoria ou com baixa tolerância ao risco que ainda desejam alguma exposição ao crescimento.',
            pros_pt: ['Baixa volatilidade com alocação significativa em títulos', 'Ampla diversificação global para um fundo conservador', 'Taxa de despesas muito baixa de 0,12%', 'Rebalanceamento automático dentro do fundo'],
            cons_pt: ['Alocação fixa não se ajusta com a idade', 'Potencial de alta limitado em mercados de ações fortes', 'Pode não fornecer crescimento suficiente para investidores mais jovens'],
            shortDesc_fr: 'Investit dans un mix de fonds Vanguard avec environ 40 % en actions et 60 % en obligations, cherchant un revenu actuel et une appréciation faible à modérée du capital.',
            description_fr: 'Le Fonds Vanguard LifeStrategy Conservative Growth suit une stratégie d\'allocation d\'environ 60 % en obligations et 40 % en actions. Cette allocation conservatrice offre stabilité et revenu tout en maintenant une exposition aux actions.',
            bestFor_fr: 'Participants proches de la retraite ou à faible tolérance au risque souhaitant néanmoins une certaine exposition à la croissance.',
            pros_fr: ['Faible volatilité avec une allocation obligataire significative', 'Large diversification mondiale pour un fonds conservateur', 'Très faible ratio de frais de 0,12 %', 'Rééquilibrage automatique au sein du fonds'],
            cons_fr: ['L\'allocation fixe ne s\'ajuste pas avec l\'âge', 'Potentiel haussier limité en marchés actions forts', 'Peut ne pas offrir suffisamment de croissance pour les jeunes investisseurs'],
            shortDesc_de: 'Investiert in einen Mix aus Vanguard-Fonds mit ca. 40 % Aktien und 60 % Anleihen für laufende Erträge und moderates Kapitalwachstum.',
            description_de: 'Der Vanguard LifeStrategy Conservative Growth Fund folgt einer Strategie von ca. 60 % Anleihen und 40 % Aktien. Die konservative Aufteilung bietet Stabilität und Erträge bei gleichzeitiger Aktienexposition.',
            bestFor_de: 'Teilnehmer kurz vor der Rente oder mit geringer Risikobereitschaft, die dennoch etwas Wachstum möchten.',
            pros_de: ['Geringe Volatilität mit bedeutendem Anleihenanteil', 'Breite globale Diversifikation für einen konservativen Fonds', 'Sehr niedrige Kostenquote von 0,12 %', 'Automatisches Rebalancing im Fonds'],
            cons_de: ['Feste Aufteilung passt sich nicht dem Alter an', 'Begrenztes Aufwärtspotenzial in starken Aktienmärkten', 'Möglicherweise nicht genug Wachstum für jüngere Anleger'],
            shortDesc_ru: 'Инвестирует в сочетание фондов Vanguard примерно с 40% акций и 60% облигаций, нацелено на текущий доход и низкий/умеренный прирост капитала.',
            description_ru: 'Фонд Vanguard LifeStrategy Conservative Growth следует стратегии распределения около 60% в облигации и 40% в акции. Консервативное распределение обеспечивает стабильность и доход при сохранении доли в акциях.',
            bestFor_ru: 'Участники, близкие к пенсии, или с низкой толерантностью к риску, желающие некоторой экспозиции на рост.',
            pros_ru: ['Низкая волатильность при значительной доле облигаций', 'Широкая глобальная диверсификация для консервативного фонда', 'Очень низкий коэффициент расходов 0,12%', 'Автоматическая ребалансировка внутри фонда'],
            cons_ru: ['Фиксированное распределение не корректируется с возрастом', 'Ограниченный потенциал роста на сильных рынках акций', 'Может не обеспечить достаточного роста для молодых инвесторов']
        },

        puritan: {
            id: 'puritan',
            type: 'Allocation Fund',
            name: 'Fidelity Puritan K6 Fund (FPKFX)',
            badge: '',
            shortDesc: 'An actively managed balanced fund investing approximately 60% in stocks and 40% in bonds, seeking income and capital growth consistent with reasonable risk.',
            riskLevel: 'Moderate',
            stockBond: '60% Stocks / 40% Bonds',
            expenseRatio: '0.34%',
            turnover: 'Moderate',
            minInvestment: 'None',
            bestFor: 'Participants seeking a single balanced fund with active management and a moderate risk profile.',
            performance: { yr1: '13.61%', yr3: '16.74%', yr5: '9.47%', yr10: 'N/A', sinceInception: '9.47%' },
            description: 'The Fidelity Puritan K6 Fund seeks income and capital growth consistent with reasonable risk. It invests approximately 60% in stocks and other equity securities and the remainder in bonds and other debt securities, including lower-quality debt securities. The fund invests at least 25% of total assets in fixed-income senior securities and may invest in both domestic and foreign issuers. Unlike the index-based Vanguard options, the Puritan fund relies on Fidelity\'s research team to actively select individual securities.',
            allocation: [
                '~60% Equities (U.S. and International)',
                '~40% Fixed Income (Investment-grade, high-yield, and other bonds)',
                'At least 25% in fixed-income senior securities',
                'Actively managed with flexibility to adjust holdings'
            ],
            pros: ['Active management can potentially add value in changing markets', 'Balanced approach seeks both income and capital growth', 'Manager flexibility to adjust to market conditions', 'K6 share class offers institutional pricing'],
            cons: ['Higher expense ratio (0.34%) than index-based alternatives', 'Active management does not guarantee outperformance', 'Less transparency in holdings compared to index funds'],
            shortDesc_es: 'Un fondo balanceado de gestión activa que invierte aproximadamente 60% en acciones y 40% en bonos, buscando ingresos y crecimiento de capital con un riesgo razonable.',
            description_es: 'El Fondo Fidelity Puritan K6 busca ingresos y crecimiento de capital con un riesgo razonable. Invierte aproximadamente un 60% en acciones y el resto en bonos y otros valores de deuda. A diferencia de las opciones indexadas, este fondo depende del equipo de Fidelity para seleccionar activamente los valores.',
            bestFor_es: 'Participantes que buscan un fondo balanceado con gestión activa y un perfil de riesgo moderado.',
            pros_es: ['La gestión activa puede añadir valor en mercados cambiantes', 'El enfoque balanceado busca tanto ingresos como crecimiento de capital', 'Flexibilidad del gestor para adaptarse a las condiciones del mercado', 'La clase K6 ofrece precios institucionales'],
            cons_es: ['Mayor ratio de gastos (0.34%) que las alternativas indexadas', 'La gestión activa no garantiza rendimientos superiores', 'Menor transparencia en las posiciones comparado con los fondos indexados'],
            shortDesc_zh: '主动管理的平衡基金，约60%投资于股票，40%投资于债券，以合理风险寻求收入和资本增长。',
            description_zh: 'Fidelity Puritan K6基金以合理风险寻求收入和资本增长。约60%投资于股票，其余投资于债券和债务证券。与指数化Vanguard选项不同，该基金依赖富达研究团队主动选股。',
            bestFor_zh: '寻求具有主动管理和中等风险配置的单一平衡基金的参与者。',
            pros_zh: ['主动管理在变化市场中可能增加价值', '平衡方式同时追求收入和资本增长', '基金经理灵活适应市场条件', 'K6股份类别提供机构定价'],
            cons_zh: ['费用率(0.34%)高于指数类替代品', '主动管理不保证超额表现', '与指数基金相比持仓透明度较低'],
            shortDesc_ja: 'アクティブ運用のバランスファンドで約60%を株式・40%を債券に投資し、適切なリスクで収益とキャピタルゲインを目指します。',
            description_ja: 'Fidelity Puritan K6ファンドは適切なリスクのもとで収益と資本成長を目指します。約60%を株式・残りを債券に投資します。インデックス型のVanguardとは異なり、Fidelityのリサーチチームが個別証券を積極的に選択します。',
            bestFor_ja: 'アクティブ運用と中程度のリスクプロファイルを持つ単一バランスファンドを求める参加者。',
            pros_ja: ['変化する市場でアクティブ運用が価値を加える可能性', 'バランス型の運用で収益と資本成長の両方を追求', '市場環境に適応するファンドマネージャーの柔軟性', 'K6クラスは機関投資家価格を提供'],
            cons_ja: ['インデックス代替品より高い経費率（0.34%）', 'アクティブ運用はアウトパフォームを保証しない', 'インデックスファンドより保有銘柄の透明性が低い'],
            shortDesc_tl: 'Isang aktibong pinamamahalaan na balanced fund na namumuhunan ng humigit-kumulang 60% sa stocks at 40% sa bonds, naghahanap ng kita at paglago ng kapital na may makatwirang panganib.',
            description_tl: 'Ang Fidelity Puritan K6 Fund ay naghahanap ng kita at paglago ng kapital na may makatwirang panganib. Namumuhunan ito ng humigit-kumulang 60% sa stocks at ang natitira sa bonds. Hindi tulad ng mga index-based na opsyon ng Vanguard, umaasa ito sa research team ng Fidelity para aktibong pumili ng mga securities.',
            bestFor_tl: 'Mga kalahok na naghahanap ng isang balanced fund na may aktibong pamamahala at katamtamang risk profile.',
            pros_tl: ['Ang aktibong pamamahala ay potensyal na makapagdagdag ng halaga sa pagbabago ng mga merkado', 'Ang balanced na diskarte ay naghahanap ng kita at paglago ng kapital', 'Kakayahang umangkop ng manager sa mga kondisyon ng merkado', 'Ang K6 share class ay nag-aalok ng institutional na pagpepresyo'],
            cons_tl: ['Mas mataas na expense ratio (0.34%) kaysa sa mga index-based na alternatibo', 'Ang aktibong pamamahala ay hindi ginagarantiyahan ang outperformance', 'Mas kaunting transparency sa mga holdings kumpara sa index funds'],
            shortDesc_pt: 'Um fundo equilibrado de gestão ativa que investe aproximadamente 60% em ações e 40% em títulos, buscando renda e crescimento de capital com risco razoável.',
            description_pt: 'O Fundo Fidelity Puritan K6 busca renda e crescimento de capital com risco razoável. Investe aproximadamente 60% em ações e o restante em títulos. Ao contrário das opções indexadas da Vanguard, este fundo depende da equipe de pesquisa da Fidelity para selecionar ativamente os títulos.',
            bestFor_pt: 'Participantes que buscam um único fundo equilibrado com gestão ativa e perfil de risco moderado.',
            pros_pt: ['Gestão ativa pode agregar valor em mercados em mudança', 'Abordagem equilibrada busca tanto renda quanto crescimento de capital', 'Flexibilidade do gestor para se adaptar às condições do mercado', 'Classe de ações K6 oferece preços institucionais'],
            cons_pt: ['Taxa de despesas mais alta (0,34%) do que alternativas indexadas', 'Gestão ativa não garante desempenho superior', 'Menor transparência nas posições em comparação com fundos de índice'],
            shortDesc_fr: 'Un fonds équilibré à gestion active investissant environ 60 % en actions et 40 % en obligations, cherchant revenus et croissance du capital avec un risque raisonnable.',
            description_fr: 'Le Fonds Fidelity Puritan K6 recherche revenus et croissance du capital avec un risque raisonnable. Il investit environ 60 % en actions et le reste en obligations. Contrairement aux options indexées Vanguard, ce fonds s\'appuie sur l\'équipe de recherche Fidelity pour sélectionner activement les titres.',
            bestFor_fr: 'Participants cherchant un fonds équilibré unique avec gestion active et profil de risque modéré.',
            pros_fr: ['La gestion active peut potentiellement ajouter de la valeur', 'L\'approche équilibrée vise revenus et croissance du capital', 'Flexibilité du gérant pour s\'adapter aux conditions de marché', 'La classe K6 offre une tarification institutionnelle'],
            cons_fr: ['Ratio de frais plus élevé (0,34 %) que les alternatives indexées', 'La gestion active ne garantit pas une surperformance', 'Moins de transparence des positions qu\'un fonds indiciel'],
            shortDesc_de: 'Aktiv verwalteter Mischfonds mit ca. 60 % Aktien und 40 % Anleihen, strebt Erträge und Kapitalwachstum bei vertretbarem Risiko an.',
            description_de: 'Der Fidelity Puritan K6 strebt Erträge und Kapitalwachstum bei vertretbarem Risiko an. Ca. 60 % in Aktien, Rest in Anleihen. Im Gegensatz zu Vanguard-Indexfonds wählt das Fidelity-Forscherteam aktiv Wertpapiere aus.',
            bestFor_de: 'Teilnehmer, die einen einzigen ausgewogenen Fonds mit aktivem Management und moderatem Risikoprofil suchen.',
            pros_de: ['Aktives Management kann in sich wandelnden Märkten Mehrwert schaffen', 'Ausgewogener Ansatz strebt Erträge und Kapitalwachstum an', 'Flexibilität des Managers bei Marktanpassungen', 'K6-Anteilsklasse bietet institutionelle Konditionen'],
            cons_de: ['Höhere Kostenquote (0,34 %) als Indexalternativen', 'Aktives Management garantiert keine Outperformance', 'Weniger Transparenz bei Positionen als bei Indexfonds'],
            shortDesc_ru: 'Активно управляемый сбалансированный фонд с инвестициями около 60% в акции и 40% в облигации, нацелен на доход и прирост капитала при разумном риске.',
            description_ru: 'Фонд Fidelity Puritan K6 стремится к доходу и приросту капитала при разумном риске. Инвестирует около 60% в акции и остальное в облигации. В отличие от индексных опций Vanguard, команда Fidelity активно отбирает ценные бумаги.',
            bestFor_ru: 'Участники, ищущие единый сбалансированный фонд с активным управлением и умеренным риском.',
            pros_ru: ['Активное управление может добавить ценность на изменчивых рынках', 'Сбалансированный подход нацелен на доход и прирост капитала', 'Гибкость управляющего для адаптации к рыночным условиям', 'Класс акций K6 предлагает институциональные цены'],
            cons_ru: ['Более высокий коэффициент расходов (0,34%), чем у индексных альтернатив', 'Активное управление не гарантирует превышение рынка', 'Меньшая прозрачность позиций по сравнению с индексными фондами']
        },

        wellesley: {
            id: 'wellesley',
            type: 'Allocation Fund',
            name: 'Vanguard Wellesley Income Admiral (VWIAX)',
            badge: '',
            shortDesc: 'A conservative allocation fund investing approximately 60-65% in bonds and 35-40% in dividend-paying stocks, focused on income and capital preservation.',
            riskLevel: 'Conservative',
            stockBond: '35-40% Stocks / 60-65% Bonds',
            expenseRatio: '0.16%',
            turnover: 'Low to Moderate',
            minInvestment: 'None',
            bestFor: 'Participants at or near retirement who prioritize income and capital preservation over growth.',
            performance: { yr1: '10.84%', yr3: '9.20%', yr5: '5.23%', yr10: '6.46%' },
            description: 'The Vanguard Wellesley Income Admiral Fund seeks long-term growth of income and a high and sustainable level of current income, along with moderate long-term capital appreciation. The fund invests approximately 60-65% of its assets in investment-grade fixed income securities, including corporate, U.S. Treasury, and government agency bonds, as well as mortgage-backed securities. The remaining 35-40% is invested in common stocks of companies with a history of above-average dividends or expectations of increasing dividends.',
            allocation: [
                '~60-65% Investment-grade fixed income (corporate, Treasury, agency, MBS)',
                '~35-40% Equities (high-quality, dividend-paying stocks)',
                'Managed by Wellington Management Company'
            ],
            pros: ['Strong emphasis on income and capital preservation', 'Managed by Wellington Management, one of the oldest investment firms', 'Low expense ratio of 0.16% for an actively managed fund', 'Focus on dividend-paying stocks provides income stability'],
            cons: ['Limited growth potential in strong equity markets', 'Not suitable for younger participants seeking aggressive growth', 'Currently on Watch status in the plan monitoring report'],
            shortDesc_es: 'Un fondo de asignación conservadora que invierte aproximadamente 60-65% en bonos y 35-40% en acciones con dividendos, enfocado en ingresos y preservación de capital.',
            description_es: 'El Fondo Vanguard Wellesley Income Admiral busca crecimiento de ingresos a largo plazo y un nivel alto y sostenible de ingresos actuales. Invierte aproximadamente el 60-65% en renta fija de grado de inversión y el 35-40% restante en acciones ordinarias de empresas con historial de dividendos superiores al promedio.',
            bestFor_es: 'Participantes en la jubilación o próximos a ella que priorizan los ingresos y la preservación de capital sobre el crecimiento.',
            pros_es: ['Fuerte énfasis en ingresos y preservación de capital', 'Gestionado por Wellington Management, una de las firmas más antiguas', 'Bajo ratio de gastos de 0.16% para un fondo de gestión activa', 'El enfoque en dividendos proporciona estabilidad de ingresos'],
            cons_es: ['Potencial de crecimiento limitado en mercados alcistas', 'No adecuado para participantes jóvenes que buscan crecimiento agresivo', 'Actualmente en estado de Vigilancia en el informe de seguimiento del plan'],
            shortDesc_zh: '保守配置基金，约60-65%投资于债券，35-40%投资于派息股票，专注于收入和资本保全。',
            description_zh: 'Vanguard Wellesley Income Admiral基金追求长期收入增长和高水平可持续的当期收入。约60-65%投资于投资级固定收益，其余35-40%投资于有高于平均股息历史的普通股。',
            bestFor_zh: '在退休或临近退休的参与者，优先考虑收入和资本保全而非增长。',
            pros_zh: ['强调收入和资本保全', '由惠灵顿管理公司管理，最古老的投资公司之一', '主动管理基金中费用率较低：0.16%', '专注派息股票提供收入稳定性'],
            cons_zh: ['强势股票市场中增长潜力有限', '不适合寻求积极增长的年轻参与者', '目前在计划监控报告中处于观察状态'],
            shortDesc_ja: '約60-65%を債券・35-40%を配当株式に配分する保守型ファンドで、収益と資本保全に重点を置きます。',
            description_ja: 'Vanguard Wellesley Income Admiralファンドは長期的な収益成長と高水準の安定した収益を追求します。約60-65%を投資適格固定収益に、残りの35-40%を平均以上の配当実績を持つ普通株に投資します。',
            bestFor_ja: '退職中または退職が近く、成長より収益と資本保全を優先する参加者。',
            pros_ja: ['収益と資本保全に強い重点', 'ウェリントン・マネジメントが管理（最古の投資会社の一つ）', 'アクティブ運用ファンドとして低い経費率0.16%', '配当株への注力が収益安定性を提供'],
            cons_ja: ['強い株式相場での成長ポテンシャルが限られる', '積極的成長を求める若い参加者には不向き', 'プランモニタリングレポートで現在ウォッチ対象'],
            shortDesc_tl: 'Isang conservative allocation fund na namumuhunan ng humigit-kumulang 60-65% sa bonds at 35-40% sa mga dividend-paying na stocks, nakatuon sa kita at pangangalaga ng kapital.',
            description_tl: 'Ang Vanguard Wellesley Income Admiral Fund ay naghahanap ng pangmatagalang paglago ng kita at mataas at napapanatiling antas ng kasalukuyang kita. Namumuhunan ito ng humigit-kumulang 60-65% sa investment-grade fixed income at ang natitirang 35-40% sa mga karaniwang stock na may kasaysayan ng mas mataas kaysa sa average na dibidendo.',
            bestFor_tl: 'Mga kalahok na nasa o malapit sa pagreretiro na inuuna ang kita at pangangalaga ng kapital kaysa sa paglago.',
            pros_tl: ['Matibay na diin sa kita at pangangalaga ng kapital', 'Pinamamahalaan ng Wellington Management, isa sa mga pinakamatandang investment firm', 'Mababang expense ratio na 0.16% para sa aktibong pinamamahalaan na pondo', 'Ang focus sa dividend-paying stocks ay nagbibigay ng katatagan ng kita'],
            cons_tl: ['Limitadong potensyal ng paglago sa malakas na equity markets', 'Hindi angkop para sa mga mas batang kalahok na naghahanap ng agresibong paglago', 'Kasalukuyang nasa Watch status sa plan monitoring report'],
            shortDesc_pt: 'Um fundo de alocação conservadora que investe aproximadamente 60-65% em títulos e 35-40% em ações pagadoras de dividendos, focado em renda e preservação de capital.',
            description_pt: 'O Fundo Vanguard Wellesley Income Admiral busca crescimento de renda a longo prazo e alto nível sustentável de renda atual. Investe aproximadamente 60-65% em renda fixa de grau de investimento e os restantes 35-40% em ações com histórico de dividendos acima da média.',
            bestFor_pt: 'Participantes na ou próximos à aposentadoria que priorizam renda e preservação de capital sobre crescimento.',
            pros_pt: ['Forte ênfase em renda e preservação de capital', 'Gerenciado pela Wellington Management, uma das firmas de investimento mais antigas', 'Baixa taxa de despesas de 0,16% para um fundo gerenciado ativamente', 'Foco em ações pagadoras de dividendos fornece estabilidade de renda'],
            cons_pt: ['Potencial de crescimento limitado em mercados de ações fortes', 'Não adequado para participantes mais jovens que buscam crescimento agressivo', 'Atualmente em status de vigilância no relatório de monitoramento do plano'],
            shortDesc_fr: 'Un fonds d\'allocation conservatrice investissant environ 60-65 % en obligations et 35-40 % en actions à dividendes, axé sur les revenus et la préservation du capital.',
            description_fr: 'Le Fonds Vanguard Wellesley Income Admiral recherche une croissance des revenus à long terme et un niveau élevé et durable de revenus actuels. Il investit environ 60-65 % en obligations investment grade et les 35-40 % restants en actions à dividendes élevés.',
            bestFor_fr: 'Participants à la retraite ou proches de la retraite privilégiant les revenus et la préservation du capital.',
            pros_fr: ['Fort accent sur les revenus et la préservation du capital', 'Géré par Wellington Management, l\'une des plus anciennes sociétés d\'investissement', 'Faible ratio de frais de 0,16 % pour un fonds à gestion active', 'L\'accent sur les actions à dividendes assure la stabilité des revenus'],
            cons_fr: ['Potentiel de croissance limité en marchés haussiers', 'Pas adapté aux jeunes participants cherchant une croissance agressive', 'Actuellement sous surveillance dans le rapport de suivi du plan'],
            shortDesc_de: 'Konservativer Allokationsfonds mit ca. 60-65 % Anleihen und 35-40 % Dividendenaktien für Erträge und Kapitalerhalt.',
            description_de: 'Der Vanguard Wellesley Income Admiral strebt langfristiges Einkommenswachstum und ein hohes, nachhaltiges laufendes Einkommen an. Ca. 60-65 % in Investment-Grade-Anleihen, die restlichen 35-40 % in Aktien mit überdurchschnittlicher Dividendenhistorie.',
            bestFor_de: 'Teilnehmer im oder kurz vor dem Ruhestand, die Erträge und Kapitalerhalt über Wachstum stellen.',
            pros_de: ['Starker Fokus auf Erträge und Kapitalerhalt', 'Verwaltet von Wellington Management, einer der ältesten Investmentgesellschaften', 'Niedrige Kostenquote von 0,16 % für einen aktiv verwalteten Fonds', 'Dividendenfokus sorgt für Einkommensstabilität'],
            cons_de: ['Begrenztes Wachstumspotenzial in starken Aktienmärkten', 'Nicht geeignet für jüngere Teilnehmer mit Wachstumsfokus', 'Derzeit unter Beobachtung im Plan-Überwachungsbericht'],
            shortDesc_ru: 'Консервативный фонд распределения активов с инвестициями около 60-65% в облигации и 35-40% в дивидендные акции, ориентирован на доход и сохранение капитала.',
            description_ru: 'Фонд Vanguard Wellesley Income Admiral стремится к долгосрочному росту дохода и высокому устойчивому текущему доходу. Около 60-65% инвестируется в инвестиционные облигации, оставшиеся 35-40% — в акции компаний с историей дивидендов выше среднего.',
            bestFor_ru: 'Участники на пенсии или близкие к ней, ставящие доход и сохранение капитала выше роста.',
            pros_ru: ['Сильный акцент на доходе и сохранении капитала', 'Управляется Wellington Management — одной из старейших инвестиционных компаний', 'Низкий коэффициент расходов 0,16% для активно управляемого фонда', 'Фокус на дивидендных акциях обеспечивает стабильность дохода'],
            cons_ru: ['Ограниченный потенциал роста на сильных рынках акций', 'Не подходит для молодых участников, ищущих агрессивного роста', 'В настоящее время находится под наблюдением в отчёте по мониторингу плана']
        }

    } // end fundData

}; // end clientConfig
